name: Security Audits

on:
  schedule:
    # Every Saturday at 1PM UTC (6AM PST)
    - cron: "0 13 * * 6"
  pull_request:
    branches: [ main ]

jobs:
  security-audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Security audit
        uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
